version: '3'

services:
  app:
    image: wendell_adriel/laravel-more
    container_name: laravel-more
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/usr/src/app
